void disp_menu();
void disp_list();
void Exit();
void About();
void Shop();
void Save_game();
void Loading();
void lignes();
void Continue();
void New_game();
void reveil();
void Color(int t,int f);
